const root = document.querySelector(":root");

const LightModeColor = () => {
  document.querySelector("body").style.backgroundColor = "#d5f0dc";
  root.style.setProperty("--logo", "#ffa811");
  root.style.setProperty("--nav-scroll-background", " rgba(26, 36, 47, 0.8)");
  root.style.setProperty("--nav-el-color", " #d5f0dc");
  root.style.setProperty("--nav-el-background", " #202c39");
  root.style.setProperty("--nav-border", " #d5f0dc");
  root.style.setProperty("--nav-signup-color", " #202c39");
  root.style.setProperty("--nav-signup-background", " #d5f0dc");
  root.style.setProperty("--form-background", " #202c39");
  root.style.setProperty("--form-boxshadow", " #202c39");
  root.style.setProperty("--form-label", " #d5f0dc");
  root.style.setProperty("--form-input-background", " white");
  root.style.setProperty("--form-input-color", " #202c39");
  root.style.setProperty("--form-submit-background", " white");
  root.style.setProperty("--form-submit-color", " #202c39");
  root.style.setProperty("--form-submit-border", " black");
  root.style.setProperty("--header-background", " transparent");
  root.style.setProperty("--header-name", " white");
  root.style.setProperty("--header-heading", " white");
  root.style.setProperty("--header-description", " white");
  root.style.setProperty("--about-background", " #d5f0dc");
  root.style.setProperty("--about-top-heading", " black");
  root.style.setProperty("--about-top-description", " black");
  root.style.setProperty("--about-bottom-svg", " ");
  root.style.setProperty("--about-bottom-heading", " black");
  root.style.setProperty("--about-bottom-description", " black");
  root.style.setProperty("--services-background", " rgba(0, 0, 0, 0.5)");
  root.style.setProperty("--services-top-heading", " white");
  root.style.setProperty("--services-top-description", " white");
  root.style.setProperty("--services-bottom-el-background", " #d5f0dc");
  root.style.setProperty("--services-bottom-el-boxshadow", " #202c39");
  root.style.setProperty("--services-bottom-el-svg", " ");
  root.style.setProperty("--services-bottom-el-heading", " #202c39");
  root.style.setProperty("--products-background", " #d5f0dc");
  root.style.setProperty("--products-top-heading", " black");
  root.style.setProperty("--products-top-description", " black");
  root.style.setProperty("--products-bottom-el-background", " #0b7a75");
  root.style.setProperty("--products-bottom-el-boxshadow", " #202c39");
  root.style.setProperty("--products-bottom-el-name", " white");
  root.style.setProperty("--products-bottom-el-price", " white");
  root.style.setProperty("--products-bottom-el-button-background", " #d5f0dc");
  root.style.setProperty("--products-bottom-el-button-color", " #202c39");
  root.style.setProperty("--cart-background", " #202c39");
  root.style.setProperty("--cart-color", " #d5f0dc");
  root.style.setProperty("--shopping-background", " #202c39");
  root.style.setProperty("--shopping-heading", " white");
  root.style.setProperty("--shopping-remove-background", " white");
  root.style.setProperty("--shopping-remove-color", " #202c39");
  root.style.setProperty("--shopping-el-name", " #d5f0dc");
  root.style.setProperty("--shopping-el-price", " #d5f0dc");
  root.style.setProperty("--shopping-total", " #d5f0dc");
  root.style.setProperty("--shopping-total-price", " #d5f0dc");
  root.style.setProperty("--shopping-buy-background", " white");
  root.style.setProperty("--shopping-buy-color", " #202c39");
  root.style.setProperty("--footer-background", " #202c39");
  root.style.setProperty("--footer-quotes-heading", " #d5f0dc");
  root.style.setProperty("--footer-quotes-description", " #d5f0dc");
  root.style.setProperty("--footer-link-heading", " #d5f0dc");
  root.style.setProperty("--footer-link", " #d5f0dc");
};

export default LightModeColor;
